# This is a comment.
# This file uses the TOML format. Comments, indicated by hashtags outside of quotes, will not be processed.
# Learn more about TOML format here: https://toml.io/en/
# Text within quotes uses Markdown format, where hashtags indicate heading levels.
# Learn more about Markdown here: https://www.markdownguide.org/getting-started/
# Settings start below.

title = "AI SimBot"
# See all timezones for log: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
timezone = "UTC"
allow_text_chat = false
error_message = "ğŸ˜ Oops! An unexpected error occurred. Please try again. If the error persists, please contact the administrator."
user_name = "Nurse"
user_avatar = "assets/images/User.png"
assistant_name = "Jordan"
assistant_avatar = "assets/images/Assistant.jpg"

# Pictures on the sidebar
assistant_interview = "assets/images/Jordan.jpg"
assistant_feedback = "assets/images/Debriefer.jpg"

#--------------------
# Intro message will be displayed before users start chatting.

intro = '''
## Welcome to Dr. Kimâ€™s AI SimBot.

This AI-powered simulation helps you practice advanced communication skills for screening substance use in adolescent patients. You can use this tool anytime, anywhere, to engage in realistic scenarios that prepare you for real-world clinical settings. My goal is to enhance your learning experience and build your confidence and competence in nursing practice. Let's get started!

## Scenario

Jordan, a 17-year-old, non-binary student is visiting your outpatient clinic for a physical exam needed for school sports participation. Youâ€™ll act as the nurse, administering the CRAFFT tool and providing brief counseling and referral to treatment if necessary.

## Instructions

* Before getting started, make sure you have the CRAFFT tool available. Youâ€™ll need to reference this during the session.Â 
* When you're finished talking to Jordan, click theÂ â€™Nextâ€™Â button.
* Dr. Casey, a virtual debriefer, will begin a personalized debriefing session with you. When youâ€™re finished, click theÂ â€™Nextâ€™Â button.Â 
* Be sure to click theÂ â€˜Download Transcriptâ€™Â button to get a copy of conversation with Jordan and Dr. Casey, as youâ€™ll need it to complete the assignment in Canvas!
* Now that you know what to expect, enter the password and clickÂ â€˜Loginâ€™Â to test your microphone and speaker and begin.
'''

warning = "This simulation might evoke strong emotions or may be distressing for individuals with personal experiences related to substance use or addiction. If you feel overwhelmed by the content, please discontinue the simulation and reach out to your course faculty, or schedule an appointment with [Northeastern University Health & Counseling Services](https://uhcs.northeastern.edu/). If you or someone you know is struggling with substance use or addiction, support is available."

unavailable = '''
**ğŸ› ï¸ AISimBot is Getting a Tune-Up!**

Weâ€™re making some upgrades under the hood to make your simulation even smoother, smarter, and more realistic.

AISimBot will be back shortlyâ€”fresher than ever.

ğŸ’¡ In the meantime, take a break, grab a coffee, or imagine the perfect patient encounter. Weâ€™ll be ready when you are.

Thanks for your patience! ğŸ©ºğŸ¤–
'''

agreement = '''
This is an amazing research! You should definitely participate!
'''

#--------------------

[sidebar]
# Add or remove fields as needed.
# Key names should not contain spaces. Use the _ symbol, which will be replaced with spaces when displayed in the sidebar.

Name = "Jordan Taylor"
Age = "17"
Gender = "Non-binary"
Visit_Reason = "Routine physical exam required for school sports participation."


#--------------------


[parameters]
# Use one of the followings: alloy, ash, coral, echo, fable, onyx, nova, sage and shimmer.
# Previews of the voices are available: https://www.openai.fm/
voice = "nova"
voice_instruction = "a 17-year-old, non-binary student who plays  sports. Tone: reserved, withdrawn."
# gpt-4o-mini: fast and cheaper model but with less quality
model = "gpt-4.1"
# Specify between 0 and 2. Higher values like 0.8 will make the output more random (or creative), while lower values like 0.2 will make it more focused and deterministic.
temperature = 0.7
feedback_model = "o4-mini"
feedback_temperature = 0.0
feedback_voice = "shimmer"
feedback_voice_instruction = '''
Voice Affect: encouraging, assuring, and calm.
Delivery: Natural conversational
Emotion: express genuine warmth and care.
'''
